### ISSUE TITLE
`Service.create_job` should handle a list of circuits.

### ISSUE THREAD

**Issue by teaguetomesh** [SupertechLabs/cirq-superstaq#10]

**Comment by vtomole** [comment]
We've decided that `create_job` should just work for a list of circuits. Will re-title this issue appropriately.

**Comment by vtomole** [comment]
This is not necessary if we encourage users to use the `Sampler` instead:

```python
service = cirq_superstaq.Service(...)
q0, q1 = cirq.LineQubit.range(2)
sampler = service.sampler()
circuit = cirq.Circuit(cirq.H(q0), cirq.CNOT(q0, q1), cirq.measure(q0))
circuit2 = cirq.Circuit(cirq.X(q0), cirq.measure(q0))
print(sampler.run_batch([circuit. circuit2], repetitions=5))
```

@richrines1 @singular-value @dowusu-antwi Feel free to re-open this issue if you prefer to make `create_job` handle lists of circuits.
