### ISSUE TITLE
daily integration test failing

### ISSUE THREAD

**Issue by singular-value** [SupertechLabs/cirq-superstaq#112]
https://github.com/SupertechLabs/cirq-superstaq/actions/runs/1425994003

**Comment by vtomole** [comment]
@dowusu-antwi Did some hardware get added/taken away?

**Comment by dowusu-antwi** [comment]
Looks like `d-wave_advantage-system1.1_qpu` is offline. It was in the list last week:

![backend-display-pre-update](https://user-images.githubusercontent.com/18367737/140531211-6d3268a4-e35a-4078-95ce-b8a166c0bb77.png)

Here's the list now (with no `1.1`):

![updated_backend_list](https://user-images.githubusercontent.com/18367737/140531313-78621377-73bf-4ce6-a337-fb2d272e2639.png)
