### ISSUE TITLE
Notebook tests

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/cirq-superstaq#117]
Check to run notebooks to make sure that the notebook code still works.

**Comment by vtomole** [comment]
I'm going to take this.

**Comment by vtomole** [comment]
Whoever takes this can reference: https://github.com/quantumlib/Cirq/blob/efd3b25e83a6dacde69d7d000b7de19d8671cea8/.github/workflows/ci.yml#L297

**Comment by pgoiporia** [comment]
#249

**Comment by stephanielee9** [comment]
Duplicate of https://github.com/SupertechLabs/general-superstaq/issues/66
