### ISSUE TITLE
Make token required for IBM Q devices

### ISSUE THREAD

**Issue by dowusu-antwi** [SupertechLabs/cirq-superstaq#119]
For IBM Q device requests, check provider parameters (i.e., where provider refers to `(group, project, hub)`) and throw exception if not set.

**Comment by vtomole** [comment]
Make `ibm_token` and `ibmq_pulse` required as well. These can easily be set as env variables so hopefully that won't make the size of `cirq_superstaq.Service` too overwhelming.

**Comment by dowusu-antwi** [comment]
> Make `ibm_token` and `ibmq_pulse` required as well. These can easily be set as env variables so hopefully that won't make the size of `cirq_superstaq.Service` too overwhelming.

OK. I've been thinking and it might make more sense to require these in the `create_job` method directly.

Still working out if this is a good idea, but it doesn't look like anywhere else will need those parameters, and we should allow users to use `Service` to run on non-IBM devices without having to give the `(group, project, hub)` params.

**Comment by vtomole** [comment]
That sounds better. Let's look into it.

**Comment by dowusu-antwi** [comment]
We don't actually use the provider (group, project, hub) for anything, so we've removed those attributes in our devices. In case we need to revert functionality for some IBM Q devices, the provider is returned by `IBMQBackend.provider()`.
