### ISSUE TITLE
Change `ParallelRGate` to `ParallelPhasedXPowGate`

### ISSUE THREAD

**Issue by perlinm** [SupertechLabs/cirq-superstaq#180]
When I first wrote the CQDevice compiler, I needed some sort of gate for global X-Y rotations.  Since I'm used to thinking about rotations in terms of angles, I was basically looking for a parallel `RGate`, hence the (eventual) addition of `ParallelRGate` to `cirq-superstaq`.  The more I think about circuits and compilers, however, the more I prefer to think in terms of half turns / exponents for Pauli(-like) gates.  (EDIT: I originally proposed *adding* a `ParallelPhasedXPowGate`; I am now proposing to *replace* `ParallelRGate` with `ParallelPhasedXPowGate`.)

Related: is it possible to have some sort of generic / template similar to [`ParallelGate`](https://quantumai.google/reference/python/cirq/ops/ParallelGate) for which `mypy` would recognize the type of `sub_gate`?  That is, we could get rid of `ParallelRGate` entirely if, after we define `parallel_rgate = ParallelGateLike(RGate(...), ...)`, we could get `mypy` to recognize that `isinstance(parallel_rgate.sub_gate, RGate)`.  In this case we would not need `ParallelPhasedXPowGate`, which (like `ParallelRGate`) I really only need for the sake of type safety.

@vtomole @richrines1 @dowusu-antwi

**Comment by vtomole** [comment]
Do you want to replace `ParallelRGate` with `ParallelXPowGate` or do you want to have both?

**Comment by perlinm** [comment]
I guess I would only need `ParallelXPowGate`, although a generic `ParallelGate` with typing-exposed `sub_gate` would be preferred / ideal.

**Comment by richrines1** [comment]
imo it's not bad to have (one or both) of these custom gate definitions, as it also nicely differentiates/provides information about the specific low-level operations implemented in hardware

> although a generic `ParallelGate` with typing-exposed `sub_gate` would be preferred / ideal

do you have an example of how you would use this/where `cirq.ParallelGate` doesn't work well?

**Comment by perlinm** [comment]
> do you have an example of how you would use this/where cirq.ParallelGate doesn't work well?

I guess the example I had in mind was something like
```python
parallel_gate = cirq.ParallelGate(
    cirq.PhasedXPowGate(phase_exponent=0.5, exponent=0.25),
    len(all_qubits),
)
print(parallel_gate.sub_gate.exponent)
```
which prompts `mypy` to throw `error: "Gate" has no attribute "exponent"  [attr-defined]`.

Now that I think of it though, the only place I actually use this at the moment is in `ss.resource_counters.total_global_op_pi_time` (which should be renamed to `ss.resource_counters.total_global_rgate_time`), and there I have to check for `isinstance(op.gate, cirq_superstaq.ParallelRGate)` anyways, and it wouldn't be that much more work to check `isinstance(op.gate, cirq_superstaq.ParallelGate) and isinstance(op.gate.sub_gate, cirq_superstaq.RGate)`, so I maybe *could* just use `cirq.ParallelGate`...  In that case all I really want (instead of `ParallelRGate` or `ParallelPhasedXPowGate`) is a `ParallelGate` with "clean" pretty printing, i.e. what we do for `ParallelRGate`:
```
──Gate(*params)──
  │
──#2─────────────
  │
──#3─────────────
```
instead of
```
──Gate(*params)──

──Gate(*params)──

──Gate(*params)──
```
Maybe we should just remove `ParallelRGate` from `cirq_superstaq` altogether and write a wrapper for `cirq.ParallelGate` with nicer printing?

**Comment by perlinm** [comment]
> imo it's not bad to have (one or both) of these narrower custom gate definitions, as it also nicely differentiates/provides information about the specific low-level operations implemented in hardware

I guess that's true, but my current thought is that it seems silly to define custom gates just so that we could call `op.gate.attribute` instead of `op.gate.attribute`.

**Comment by richrines1** [comment]
i think don't think it's too awkward to make it a keyword as well. but I'd also be in favor of allowing them all to be positional, honestly I wish the cirq gates weren't keyword-only

**Comment by perlinm** [comment]
Agree that I wish `cirq` wasn't keyword-only on this.  Final nitpicky question (I hope): if the arguments are to be positional, should we choose the `cirq` "convention" of `phase_exponent ~ phi` before `exponent ~ theta`, or the `RGate` convention of `theta` before `phi`?  I lean `RGate`, but I'm

**Comment by stephanielee9** [comment]
From Michael: "I think we can just close it, it might be kind of nice to have but it doesn't matter. Also it doesn't reflect how the rest of CQ thinks about global pulses"
