### ISSUE TITLE
return `CompilerOutput` from `neutral_atom_compile`

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/cirq-superstaq#221]
We don't return ` cirq_superstaq.compiler_output.CompilerOutput` in this function but maybe this is something we want to create an issue for. 

Anyway, i'm surprised that this is passing since we return ` pulses = applications_superstaq.converters.deserialize(json_dict["pulses"])`

_Originally posted by @vtomole in https://github.com/SupertechLabs/cirq-superstaq/pull/219#discussion_r846193797_

**Comment by stephanielee9** [comment]
https://github.com/SupertechLabs/cirq-superstaq/pull/361

**Comment by stephanielee9** [comment]
Next time we have to support this endpoint, we should remove it
