### ISSUE TITLE
Testing images in jupyter notebooks with pytest-notebook

### ISSUE THREAD

**Issue by pgoiporia** [SupertechLabs/cirq-superstaq#252]
While addressing #117, I couldn't run notebook tests on `examples/ibmq_compile.ipynb` because the notebook prints images for pulse schedules which change on each iteration. To elaborate, the pulse schedule drawing mentions the schedule id number at the top, which is unique and changes on each run, so the id is different in the notebook run that I submit to github and the one which is produced when github runs the notebook test (attaching image for reference).
<img width="620" alt="pulse_schedule" src="https://user-images.githubusercontent.com/85507449/170150986-a325f7c8-08f5-4087-8aba-c91cabb9f36d.png">

I've tried a couple of different ways (see https://github.com/jupyter/nbclient/pull/151) without success. Ideally, we should be able to either ignore all cells with images, or less preferably go into the notebook metadata and specify which cells should be ignored by pytest-notebook.

I'll add that this is one of a number of roadblocks I have faced with pytest-notebook, and while I found ways to deal with the other ones, it did take a while - which makes me wonder if there is a preferred alternative to pytest-notebook.

**Comment by singular-value** [comment]
Interesting.

Another solution would be to change SuperstaQ to give a more sensible name to these pulse schedules.

However, this too will break down whenever IBM calibrations change enough to modify the pixels in the output schedule (I expect this would happen every couple weeks). So the ignoring-images idea sounds good.

**Comment by stephanielee9** [comment]
not worth the effort
