### ISSUE TITLE
Make api_key the first argument of `Service`

### ISSUE THREAD

**Issue by singular-value** [SupertechLabs/cirq-superstaq#261]
We did the same thing in qss.SuperstaQProvider in https://github.com/SupertechLabs/qiskit-superstaq/pull/138

**Comment by singular-value** [comment]
Triaging to @PalashGoiporia when he returns next week. Some notebooks may need to be updated.

**Comment by pgoiporia** [comment]
Working on this now

**Comment by singular-value** [comment]
> Triaging to @PalashGoiporia when he returns next week. Some notebooks may need to be updated.

@PalashGoiporia #264 still needs the examples/ notebooks to be updated (can drop `api_key=`)

**Comment by vtomole** [comment]
Ideally Github Actions would look out for us on this. In addition to the notebook tests, I've filed https://github.com/SupertechLabs/applications-superstaq/issues/66

**Comment by pgoiporia** [comment]
> > Triaging to @PalashGoiporia when he returns next week. Some notebooks may need to be updated.
> 
> @PalashGoiporia #264 still needs the examples/ notebooks to be updated (can drop `api_key=`)

I assume these changes also have to be made within the cirq_superstaq codebase (i.e. all of the scripts)?

**Comment by pgoiporia** [comment]
> Ideally Github Actions would look out for us on this. In addition to the notebook tests, I've filed [SupertechLabs/applications-superstaq#66](https://github.com/SupertechLabs/applications-superstaq/issues/66)

I'm self assigning this

**Comment by vtomole** [comment]
Okay, we'll have to address https://github.com/SupertechLabs/cirq-superstaq/issues/263 before doing that one.

**Comment by singular-value** [comment]
> Ideally Github Actions would look out for us on this. In addition to the notebook tests, I've filed [SupertechLabs/applications-superstaq#66](https://github.com/SupertechLabs/applications-superstaq/issues/66)

For this particular change, the old notebooks still work, more of a style thing.

**Comment by pgoiporia** [comment]
> > > Triaging to @PalashGoiporia when he returns next week. Some notebooks may need to be updated.
> > 
> > 
> > @PalashGoiporia #264 still needs the examples/ notebooks to be updated (can drop `api_key=`)
> 
> I assume these changes also have to be made within the cirq_superstaq codebase (i.e. all of the scripts)?

@singular-value thoughts on this before I merge #264?

**Comment by pgoiporia** [comment]
#264
