### ISSUE TITLE
Support for qubos

### ISSUE THREAD

**Issue by teaguetomesh** [SupertechLabs/cirq-superstaq#28]
1. Common code goes in application-superstaq: conversion functions, take a qubo and convert to model, take recarray output string and convert to real recarray.
2. cirq-superstaq imports application-superstaq: service.py (gets back recarray string) and superstaq-client (does the posting)

**Comment by vtomole** [comment]
``python
import qubovert as qv
import cirq_superstaq

qubo = qv.QUBO({("hi",): 1.0, ("bestla",): -1.0, ("hi", "bestla"): 3.0})

print(qubo.solve_bruteforce())

service = cirq_superstaq.Service(
    api_key="""token""",
    verbose=True,
)

solution = service.submit_qubo(qubo, repetitions=10, target="dwave_2000")
print(solution)
```

**Comment by teaguetomesh** [comment]
This was closed by 

cirq-superstaq #29 
[applications-superstaq#2](https://github.com/SupertechLabs/applications-superstaq/pull/2)
[superstaq#738](https://github.com/SupertechLabs/SuperstaQ/pull/738)
