### ISSUE TITLE
Make css.Barrier._has_unitary() return False 

### ISSUE THREAD

**Issue by SalahedeenIssa** [SupertechLabs/cirq-superstaq#314]
Moving this https://github.com/SupertechLabs/general-superstaq/issues/118 issue into cirq-superstaq

**Comment by richrines1** [comment]
discussed offline, decided not to do this because it breaks `cirq.unitary(circuit)` for any `circuit` containing an op s.t. `has_unitary(op)` is False and another operation follows op, e.g.
```
cirq.unitary(cirq.Circuit(cirq.X(q0), cirq.measure(q0,q1)))  # succeeds
cirq.unitary(cirq.Circuit(cirq.measure(q0,q1), cirq.X(q0)))  # fails
cirq.unitary(cirq.Circuit(cirq.X(q0), cirq.barrier(q0,q1)))  # succeeds
cirq.unitary(cirq.Circuit(cirq.barrier(q0,q1), cirq.X(q0)))  # fails iff css.Barrier._has_unitary_() is False
```
