### ISSUE TITLE
Add `XYGate to css.custom_gates`

### ISSUE THREAD

**Issue by pgoiporia** [SupertechLabs/cirq-superstaq#322]
This is one of the gates used by rigetti. Adding it in anticipation of adding Aspen-11 pulse optimizations.
https://arxiv.org/pdf/1912.04424.pdf

**Comment by vtomole** [comment]
`XYGate` is the [cirq.ISwapPowGate](https://github.com/quantumlib/Cirq/blob/f39bb8a355029ce5ac368d6549747d00f6a366de/cirq-rigetti/cirq_rigetti/quil_output.py#L163). IMO, adding `XYGate=ISwapPowGate` to `css.custom_gates` is not worth it. Please re-open if you think otherwise.

**Comment by pgoiporia** [comment]
@perlinm thoughts?

**Comment by perlinm** [comment]
The two gates are not equal.  Simple check: Rigetti's `XYGate` has **two** free parameters (not counting a global phase), whereas the `cirq.ISwapPowGate` has only one.  The `XYGate` is more like a "`PhasedISwapPowGate`".

**Comment by vtomole** [comment]
> more like

By "more like", how are they different?

**Comment by perlinm** [comment]
Oh haha I just realized that a [`cirq.PhasedISwapPowGate`](https://quantumai.google/reference/python/cirq/PhasedISwapPowGate) actually exists.  That's exactly what we need.  Closing.
