### ISSUE TITLE
support parameter arguments in custom gates

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/cirq-superstaq#351]
all gates should support symbolic expressions for numerical arguments so that they're compatible with e.g. `cirq.ParamResolver`s. Currently our support is inconsistent, for example `ZZSwapGate` accepts parametrized values, but `AceCR`, `RGate` and `ParallelRGate` do not

**Comment by perlinm** [comment]
This is a good idea to implement, but note that downstream compilers will need to check for symbolic gates and possibly throw an exception if they find one.

**Comment by richrines1** [comment]
we should be checking this already - most built in cirq gates already support parametrization. will create another issue
