### ISSUE TITLE
Implement `cirq.Sampler`

### ISSUE THREAD

**Issue by singular-value** [SupertechLabs/cirq-superstaq#67]
Support run-batch (connect to multi_job server endpoint) along with this.

**Comment by vtomole** [comment]
This can be done when implementing a `cirq.Sampler`: https://github.com/quantumlib/Cirq/blob/32e1d1e6037bc11535209da3d24072ac11fb89f6/cirq-core/cirq/work/sampler.py#L198-L255

**Comment by vtomole** [comment]
I've changed this to high priority and re-worded the title. @dowusu-antwi please reference https://github.com/quantumlib/Cirq/blob/master/cirq-ionq/cirq_ionq/sampler.py

**Comment by dowusu-antwi** [comment]
The sampler implementation works:
![run-batch-works](https://user-images.githubusercontent.com/18367737/140557351-db603d83-3bae-4826-85c1-f4ba534a6679.png)

However, this only functions if ``Sampler`` is imported after ``Service`` in ``__init__.py``. The trouble with this is that the format tests fail (expecting alphabetically-ordered imports). (Note: `ionq` manages to get this working with importing ``Service`` after ``Sampler``)

**Comment by dowusu-antwi** [comment]
> Support run-batch (connect to multi_job server endpoint) along with this.

Do we want to add a new endpoint for sampling (including ``run_batch``)?

**Comment by vtomole** [comment]
No, the `multi_job server endpoint` was removed and the existing `PostJob` endpoint allows the submission of multiple circuits. The sampler already implements `run_batch` so we don't have to.

**Comment by dowusu-antwi** [comment]
Got it, sounds good.
