### ISSUE TITLE
`create_job()` shouldn't include unset values in request

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/cirq-superstaq#90]
currently `ibmq_token`, `ibmq_group`, `self.ibmq_hub`, and `ibmq_project` get sent to the server even when their value is `None`. they should be excluded from the `json_dict` in `superstaq_client.create_job()` unless they're given a value

**Comment by paaige** [comment]
Okay I just looked into this issue and it looks like it's no longer relevant (the gss client's create_job method doesn't take the ibm related variables as arguments anymore). Tagging @richrines1 to verify it's okay to close

**Comment by richrines1** [comment]
ah nice, yep i think so!
